# coding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Shop.create(name: "Friendly Books", password: "pa55word", password_confirmation: "pa55word")
Shop.create(name: "Loyal Pets", password: "42", password_confirmation: "42")
Shop.create(name: "Tremendous Tech", password: "foobar", password_confirmation: "foobar")
Shop.create(name: "Bitchin' Books", password: "admin", password_confirmation: "admin")
Shop.create(name: "okBooks", password: "12345", password_confirmation: "12345")
Shop.create(name: "Butch's Butchers", password: "qwerty", password_confirmation: "qwerty")
Shop.create(name: "Emporium", password: "asdf", password_confirmation: "asdf")
Shop.create(name: "Rhaegar's Rubies", password: "password", password_confirmation: "password")
Shop.create(name: "Green Grocers", password: "cabbage", password_confirmation: "cabbage")

Shop.create(name: "Metal heaters", password: "pa55word", password_confirmation: "pa55word")
Shop.create(name: "Detestable wrenchers", password: "42", password_confirmation: "42")
Shop.create(name: "Mega", password: "foobar", password_confirmation: "foobar")
Shop.create(name: "Master of", password: "admin", password_confirmation: "admin")
Shop.create(name: "Morrisons", password: "12345", password_confirmation: "12345")
Shop.create(name: "Peach Store", password: "qwerty", password_confirmation: "qwerty")
Shop.create(name: "Sega", password: "asdf", password_confirmation: "asdf")
Shop.create(name: "Caspian", password: "password", password_confirmation: "password")
Shop.create(name: "The phone company", password: "cabbage", password_confirmation: "cabbage")
Shop.create(name: "Astral wizards", password: "pa55word", password_confirmation: "pa55word")
Shop.create(name: "Friend finder dot co", password: "42", password_confirmation: "42")
Shop.create(name: "Technono", password: "foobar", password_confirmation: "foobar")
Shop.create(name: "Books be witchin'", password: "admin", password_confirmation: "admin")
Shop.create(name: "Not ok books", password: "12345", password_confirmation: "12345")
Shop.create(name: "Silence!", password: "qwerty", password_confirmation: "qwerty")
Shop.create(name: "I kill you!!", password: "asdf", password_confirmation: "asdf")
Shop.create(name: "Rapiers for rupies", password: "password", password_confirmation: "password")
Shop.create(name: "Maroon market", password: "cabbage", password_confirmation: "cabbage")

Customer.create(name: "Yolanda", email: "yo@gmail.com")
Customer.create(name: "Vincent", email: "vinny@hotmail.com")
Customer.create(name: "Jules", email: "JulesWinn@gmail.com")
Customer.create(name: "Marvin", email: "Mar1n@gmail.com")
Customer.create(name: "Zed", email: "manLove@hotmail.com")
Customer.create(name: "Butch", email: "hogWild@msn.com")
Customer.create(name: "B*tch", email: "Miamia@gmail.com")

Customer.create(name: "Carl", email: "SantaHigh@msn.com")
Customer.create(name: "Mazda", email: "Mazda@gmail.com")
Customer.create(name: "Achmed", email: "HowWild@msn.com")
Customer.create(name: "Πλάτον", email: "Miaumiau@gmail.com")
Customer.create(name: "Santa Claus", email: "Terotero@msn.com")
Customer.create(name: "Hello, kitty!", email: "Purupuru@gmail.com")
Customer.create(name: "私だ。こんにちは。", email: "おねがいします@gmail.com")
Customer.create(name: "The ghost of Sean Paul", email: "yes@oppai.com")
Customer.create(name: "Master exploder", email: "HaiHai@gmail.com")
Customer.create(name: "I will find you and I will **** in your sleep.", email: "hogWild@msn.com")
Customer.create(name: "Jesus", email: "τικανειςαποπσε@ελλάδα.com")
Customer.create(name: "Satan", email: "hogWild@msn.com")
Customer.create(name: "Mia", email: "ⵇⴷⵙⴷⵙⵇ@ⴼⴷⵙⵇⵙⴷ.com")
Customer.create(name: "Burt", email: "ⵙⴷⵇⴷⵙⴼⴷⵙⵇⵇⵙⴷ@msn.com")
Customer.create(name: "ⴽⵯⵇⵙⴷⵯⵃⴰⵣⴽⴷⵙⵅⵛⴽⵄⵙⴼ", email: "Miamia@gmail.com")

Product.create(name: "Cabbage", price: 3.00, quantity: 42, shop_id: 1)
Product.create(name: "Meat", price: 12.00, quantity: 7, shop_id: 2)
Product.create(name: "Necklace", price: 456.00, quantity: 2, shop_id: 3)
Product.create(name: "Owl", price: 250.00, quantity: 7, shop_id: 4)
Product.create(name: "Boat", price: 2000.00, quantity: 1, shop_id: 5)
Product.create(name: "Lemon", price: 2.00, quantity: 1, shop_id: 1)
Product.create(name: "Horse", price: 1500.00, quantity: 4, shop_id: 4)

Product.create(name: "Apple", price: 3.00, quantity: 53, shop_id: 12)
Product.create(name: "Άλογο", price: 1800.00, quantity: 3, shop_id: 23)
Product.create(name: "Handle", price: 8.00, quantity: 1234, shop_id: 18)
Product.create(name: "Gold", price: 75.00, quantity: 98, shop_id: 12)
Product.create(name: "やさい", price: 3.00, quantity: 5, shop_id: 9)
Product.create(name: "Bad food", price: 3.00, quantity: 77, shop_id: 29)
Product.create(name: "Worse food", price: 4.00, quantity: 54, shop_id: 24)
Product.create(name: "Fairy", price: 99.00, quantity: 1, shop_id: 25)
Product.create(name: "LemonLemonLemon", price: 4.00, quantity: 2, shop_id: 17)
Product.create(name: "ePhone", price: 123.00, quantity: 3, shop_id: 15)

Sale.create(quantity: 3, product_id: 1, customer_id: 1)
Sale.create(quantity: 2, product_id: 2, customer_id: 1)
Sale.create(quantity: 6, product_id: 4, customer_id: 5)
Sale.create(quantity: 2, product_id: 2, customer_id: 4)
Sale.create(quantity: 4, product_id: 5, customer_id: 3)
Sale.create(quantity: 3, product_id: 2, customer_id: 1)
Sale.create(quantity: 2, product_id: 8, customer_id: 1)
Sale.create(quantity: 6, product_id: 2, customer_id: 5)
Sale.create(quantity: 2, product_id: 9, customer_id: 4)
Sale.create(quantity: 3, product_id: 10, customer_id: 3)
Sale.create(quantity: 1, product_id: 14, customer_id: 1)
Sale.create(quantity: 6, product_id: 11, customer_id: 1)
Sale.create(quantity: 4, product_id: 13, customer_id: 3)
Sale.create(quantity: 3, product_id: 12, customer_id: 4)
Sale.create(quantity: 4, product_id: 15, customer_id: 3)
Sale.create(quantity: 6, product_id: 16, customer_id: 4)
Sale.create(quantity: 2, product_id: 17, customer_id: 5)
Sale.create(quantity: 7, product_id: 8, customer_id: 6)
Sale.create(quantity: 2, product_id: 7, customer_id: 7)
Sale.create(quantity: 4, product_id: 6, customer_id: 8)
Sale.create(quantity: 3, product_id: 5, customer_id: 9)
Sale.create(quantity: 2, product_id: 4, customer_id: 10)
Sale.create(quantity: 6, product_id: 3, customer_id: 11)
Sale.create(quantity: 2, product_id: 2, customer_id: 12)
Sale.create(quantity: 2, product_id: 1, customer_id: 12)
Sale.create(quantity: 3, product_id: 2, customer_id: 13)
Sale.create(quantity: 2, product_id: 3, customer_id: 14)
Sale.create(quantity: 6, product_id: 4, customer_id: 15)
Sale.create(quantity: 2, product_id: 5, customer_id: 16)
Sale.create(quantity: 4, product_id: 5, customer_id: 17)
Sale.create(quantity: 3, product_id: 6, customer_id: 18)
Sale.create(quantity: 2, product_id: 7, customer_id: 19)
Sale.create(quantity: 6, product_id: 8, customer_id: 20)
Sale.create(quantity: 2, product_id: 9, customer_id: 21)
Sale.create(quantity: 4, product_id: 10, customer_id: 22)
Sale.create(quantity: 8, product_id: 7, customer_id: 19)
Sale.create(quantity: 6, product_id: 8, customer_id: 20)
Sale.create(quantity: 2, product_id: 9, customer_id: 21)
Sale.create(quantity: 4, product_id: 10, customer_id: 22)
Sale.create(quantity: 3, product_id: 6, customer_id: 18)
Sale.create(quantity: 2, product_id: 7, customer_id: 19)
Sale.create(quantity: 6, product_id: 8, customer_id: 20)
Sale.create(quantity: 2, product_id: 9, customer_id: 21)
Sale.create(quantity: 4, product_id: 10, customer_id: 22)
Sale.create(quantity: 1, product_id: 7, customer_id: 19)
Sale.create(quantity: 6, product_id: 8, customer_id: 20)
